#!/bin/bash

# ==============================================
# AzerothCore Universal Deployment Script
# ==============================================
# This script deploys the complete AzerothCore stack using either:
# 1. Custom environment files (generated by setup wizard) - RECOMMENDED
# 2. Original template environment files (backward compatibility)
# All values are dynamically read from the environment files
# Usage: ./deploy-and-check.sh [--cleanup] [--skip-wizard] [--dry-run] [--force] [--use-templates]

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
NC='\033[0m' # No Color

# Script options
CLEANUP_FIRST=false
SKIP_WIZARD=false
DRY_RUN=false
FORCE=false
USE_TEMPLATES=false

# Environment file detection
ENV_TYPE=""
ENV_FILES_BASE=""

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --cleanup)
            CLEANUP_FIRST=true
            shift
            ;;
        --skip-wizard)
            SKIP_WIZARD=true
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --force)
            FORCE=true
            shift
            ;;
        --use-templates)
            USE_TEMPLATES=true
            shift
            ;;
        -h|--help)
            echo "AzerothCore Universal Deployment Script"
            echo ""
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "OPTIONS:"
            echo "  --cleanup       Clean up existing deployment before starting"
            echo "  --skip-wizard   Skip setup wizard (use existing env files)"
            echo "  --use-templates Use original template env files instead of custom ones"
            echo "  --dry-run       Show what would be done without actually doing it"
            echo "  --force         Skip confirmation prompts"
            echo "  --help          Show this help message"
            echo ""
            echo "ENVIRONMENT FILE MODES:"
            echo "  1. Custom Mode (RECOMMENDED):"
            echo "     Uses files generated by setup wizard with full customization"
            echo "  2. Template Mode (LEGACY):"
            echo "     Uses original template files for backward compatibility"
            echo ""
            echo "EXAMPLES:"
            echo "  $0                          # Auto-detect env files or run wizard"
            echo "  $0 --skip-wizard            # Deploy with existing env files (auto-detect type)"
            echo "  $0 --use-templates          # Force use of original template files"
            echo "  $0 --cleanup                # Clean up then auto-deploy"
            echo "  $0 --cleanup --skip-wizard  # Clean up then deploy with existing files"
            exit 0
            ;;
        *)
            echo "Unknown option $1"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Function to print colored output
print_status() {
    local status=$1
    local message=$2
    case $status in
        "INFO")
            echo -e "${BLUE}ℹ️  ${message}${NC}"
            ;;
        "SUCCESS")
            echo -e "${GREEN}✅ ${message}${NC}"
            ;;
        "WARNING")
            echo -e "${YELLOW}⚠️  ${message}${NC}"
            ;;
        "ERROR")
            echo -e "${RED}❌ ${message}${NC}"
            ;;
        "DANGER")
            echo -e "${RED}💀 ${message}${NC}"
            ;;
        "HEADER")
            echo -e "\n${MAGENTA}=== ${message} ===${NC}"
            ;;
    esac
}

# Function to detect which environment files are available
detect_env_files() {
    print_status "INFO" "Detecting available environment files..."

    # Check if forced to use templates
    if [ "$USE_TEMPLATES" = true ]; then
        ENV_TYPE="template"
        ENV_FILES_BASE=""
        print_status "INFO" "Forced to use template environment files"
        return 0
    fi

    # Check for custom environment files first (preferred)
    local custom_files=(
        "docker-compose-azerothcore-database-custom.env"
        "docker-compose-azerothcore-services-custom.env"
        "docker-compose-azerothcore-tools-custom.env"
    )

    local custom_files_exist=true
    for file in "${custom_files[@]}"; do
        if [ ! -f "../$file" ]; then
            custom_files_exist=false
            break
        fi
    done

    if [ "$custom_files_exist" = true ]; then
        ENV_TYPE="custom"
        ENV_FILES_BASE="-custom"
        print_status "SUCCESS" "Using custom environment files (recommended)"
        return 0
    fi

    # Check for template environment files (fallback)
    local template_files=(
        "docker-compose-azerothcore-database.env"
        "docker-compose-azerothcore-services.env"
        "docker-compose-azerothcore-tools.env"
    )

    local template_files_exist=true
    for file in "${template_files[@]}"; do
        if [ ! -f "../$file" ]; then
            template_files_exist=false
            break
        fi
    done

    if [ "$template_files_exist" = true ]; then
        ENV_TYPE="template"
        ENV_FILES_BASE=""
        print_status "WARNING" "Using template environment files (legacy mode)"
        print_status "INFO" "Consider running setup wizard for better customization"
        return 0
    fi

    # No environment files found
    ENV_TYPE="none"
    ENV_FILES_BASE=""
    print_status "ERROR" "No environment files found"
    return 1
}

# Function to read environment variable from env file (works with both types)
read_env_var() {
    local var_name=$1
    local default_value=$2
    local file_suffix=$3  # e.g., "database", "services", "tools", "modules"

    local file="docker-compose-azerothcore-${file_suffix}${ENV_FILES_BASE}.env"

    if [ -f "../$file" ]; then
        local value=$(grep "^${var_name}=" "../$file" | cut -d'=' -f2- | tr -d '"' || echo "$default_value")
        echo "${value:-$default_value}"
    else
        echo "$default_value"
    fi
}

# Function to get deployment configuration from env files
get_deployment_config() {
    # Read network and server configuration
    SERVER_ADDRESS=$(read_env_var "SERVER_ADDRESS" "127.0.0.1" "services")
    NETWORK_NAME=$(read_env_var "NETWORK_NAME" "azerothcore" "database")

    # Read external ports
    AUTH_EXTERNAL_PORT=$(read_env_var "AUTH_EXTERNAL_PORT" "3784" "services")
    WORLD_EXTERNAL_PORT=$(read_env_var "WORLD_EXTERNAL_PORT" "8215" "services")
    SOAP_EXTERNAL_PORT=$(read_env_var "SOAP_EXTERNAL_PORT" "7778" "services")
    MYSQL_EXTERNAL_PORT=$(read_env_var "MYSQL_EXTERNAL_PORT" "64306" "database")
    PMA_EXTERNAL_PORT=$(read_env_var "PMA_EXTERNAL_PORT" "8081" "tools")
    KEIRA3_EXTERNAL_PORT=$(read_env_var "KEIRA3_EXTERNAL_PORT" "4201" "tools")

    # Read database configuration
    MYSQL_ROOT_PASSWORD=$(read_env_var "MYSQL_ROOT_PASSWORD" "azerothcore123" "database")
    MYSQL_USER=$(read_env_var "MYSQL_USER" "root" "database")
    MYSQL_HOST=$(read_env_var "MYSQL_HOST" "ac-mysql" "database")
    DB_AUTH_NAME=$(read_env_var "DB_AUTH_NAME" "acore_auth" "database")
    DB_WORLD_NAME=$(read_env_var "DB_WORLD_NAME" "acore_world" "database")
    DB_CHARACTERS_NAME=$(read_env_var "DB_CHARACTERS_NAME" "acore_characters" "database")

    # Read container names
    CONTAINER_MYSQL=$(read_env_var "CONTAINER_MYSQL" "ac-mysql" "database")
    CONTAINER_DB_IMPORT=$(read_env_var "CONTAINER_DB_IMPORT" "ac-db-import" "database")
    CONTAINER_BACKUP=$(read_env_var "CONTAINER_BACKUP" "ac-backup" "database")
    CONTAINER_AUTHSERVER=$(read_env_var "CONTAINER_AUTHSERVER" "ac-authserver" "services")
    CONTAINER_WORLDSERVER=$(read_env_var "CONTAINER_WORLDSERVER" "ac-worldserver" "services")
    CONTAINER_CLIENT_DATA=$(read_env_var "CONTAINER_CLIENT_DATA" "ac-client-data" "services")

    # Read optional container names (modules layer)
    local modules_file="docker-compose-azerothcore-modules${ENV_FILES_BASE}.env"
    if [ -f "../$modules_file" ]; then
        CONTAINER_MODULES=$(read_env_var "CONTAINER_MODULES" "ac-modules" "modules")
        CONTAINER_ELUNA=$(read_env_var "CONTAINER_ELUNA" "ac-eluna" "modules")
    fi

    print_status "INFO" "Deployment configuration loaded ($ENV_TYPE mode):"
    echo "  Environment Type: $ENV_TYPE"
    echo "  Server Address: $SERVER_ADDRESS"
    echo "  Network: $NETWORK_NAME"
    echo "  MySQL Container: $CONTAINER_MYSQL"
    echo "  Auth Server Container: $CONTAINER_AUTHSERVER"
    echo "  World Server Container: $CONTAINER_WORLDSERVER"
    echo "  Ports: Auth=$AUTH_EXTERNAL_PORT, World=$WORLD_EXTERNAL_PORT, MySQL=$MYSQL_EXTERNAL_PORT"
    echo "  Databases: $DB_AUTH_NAME, $DB_WORLD_NAME, $DB_CHARACTERS_NAME"
}

# Function to execute command with dry-run support
execute_command() {
    local description=$1
    local command=$2

    if [ "$DRY_RUN" = true ]; then
        print_status "INFO" "[DRY RUN] Would execute: $description"
        echo "  Command: $command"
    else
        print_status "INFO" "Executing: $description"
        if eval "$command"; then
            print_status "SUCCESS" "Completed: $description"
        else
            print_status "WARNING" "Failed or no action needed: $description"
        fi
    fi
}

# Function to get confirmation
get_confirmation() {
    local message=$1

    if [ "$FORCE" = true ]; then
        print_status "INFO" "Force mode enabled, skipping confirmation"
        return 0
    fi

    echo -e "${YELLOW}⚠️  ${message}${NC}"
    read -p "Are you sure? (yes/no): " response
    case $response in
        yes|YES|y|Y)
            return 0
            ;;
        *)
            print_status "INFO" "Operation cancelled by user"
            exit 0
            ;;
    esac
}

# Function to check if environment files exist
check_env_files() {
    local files_exist=true
    local required_files=(
        "database"
        "services"
        "tools"
    )

    print_status "INFO" "Checking for $ENV_TYPE environment files..."

    for file_type in "${required_files[@]}"; do
        local file="docker-compose-azerothcore-${file_type}${ENV_FILES_BASE}.env"
        if [ ! -f "../$file" ]; then
            print_status "WARNING" "Missing: $file"
            files_exist=false
        else
            print_status "SUCCESS" "Found: $file"
        fi
    done

    # Check for modules file (optional)
    local modules_file="docker-compose-azerothcore-modules${ENV_FILES_BASE}.env"
    if [ -f "../$modules_file" ]; then
        print_status "SUCCESS" "Found: $modules_file (modules enabled)"
    else
        print_status "INFO" "No modules environment file (vanilla mode)"
    fi

    return $([ "$files_exist" = true ])
}

# Function to run setup wizard
run_setup_wizard() {
    print_status "HEADER" "RUNNING SETUP WIZARD"

    if [ ! -f "./setup-server.sh" ]; then
        print_status "ERROR" "Setup wizard not found: ./setup-server.sh"
        exit 1
    fi

    if [ "$DRY_RUN" = true ]; then
        print_status "INFO" "[DRY RUN] Would run setup wizard"
    else
        print_status "INFO" "Running setup wizard to generate custom environment files..."
        ./setup-server.sh

        # After wizard, re-detect environment files (should be custom now)
        if detect_env_files && check_env_files; then
            print_status "SUCCESS" "Setup wizard completed successfully"
        else
            print_status "ERROR" "Setup wizard failed to generate required files"
            exit 1
        fi
    fi
}

# Function to get all container names from environment files
get_all_container_names() {
    local containers=()

    # Add containers from database layer
    containers+=("$CONTAINER_MYSQL" "$CONTAINER_DB_IMPORT" "$CONTAINER_BACKUP")

    # Add containers from services layer
    containers+=("$CONTAINER_AUTHSERVER" "$CONTAINER_WORLDSERVER" "$CONTAINER_CLIENT_DATA")

    # Add containers from modules layer if it exists
    if [ -f "../docker-compose-azerothcore-modules${ENV_FILES_BASE}.env" ]; then
        if [ -n "$CONTAINER_MODULES" ]; then
            containers+=("$CONTAINER_MODULES")
        fi
        if [ -n "$CONTAINER_ELUNA" ]; then
            containers+=("$CONTAINER_ELUNA")
        fi
    fi

    # Add PHPMyAdmin and Keira3 (these typically use fixed names)
    containers+=("ac-phpmyadmin" "ac-keira3")

    echo "${containers[@]}"
}

# Function to perform cleanup
perform_cleanup() {
    print_status "HEADER" "CLEANING UP EXISTING DEPLOYMENT"

    get_confirmation "This will stop and remove all existing AzerothCore containers and networks."

    # Detect and load config to get container names
    if detect_env_files && check_env_files; then
        get_deployment_config

        # Stop using detected environment files
        local modules_file="docker-compose-azerothcore-modules${ENV_FILES_BASE}.env"
        execute_command "Stop modules layer ($ENV_TYPE)" \
            "cd .. && [ -f $modules_file ] && docker compose --env-file $modules_file -f docker-compose-azerothcore-modules.yml down --remove-orphans || true"

        execute_command "Stop tools layer ($ENV_TYPE)" \
            "cd .. && docker compose --env-file docker-compose-azerothcore-tools${ENV_FILES_BASE}.env -f docker-compose-azerothcore-tools.yml down --remove-orphans"

        execute_command "Stop services layer ($ENV_TYPE)" \
            "cd .. && docker compose --env-file docker-compose-azerothcore-services${ENV_FILES_BASE}.env -f docker-compose-azerothcore-services.yml down --remove-orphans"

        execute_command "Stop database layer ($ENV_TYPE)" \
            "cd .. && docker compose --env-file docker-compose-azerothcore-database${ENV_FILES_BASE}.env -f docker-compose-azerothcore-database.yml down --remove-orphans"
    fi

    # Fallback cleanup for both custom and template files
    for env_suffix in "-custom" ""; do
        execute_command "Stop tools layer (fallback$env_suffix)" \
            "cd .. && docker compose --env-file docker-compose-azerothcore-tools${env_suffix}.env -f docker-compose-azerothcore-tools.yml down --remove-orphans || true"

        execute_command "Stop services layer (fallback$env_suffix)" \
            "cd .. && docker compose --env-file docker-compose-azerothcore-services${env_suffix}.env -f docker-compose-azerothcore-services.yml down --remove-orphans || true"

        execute_command "Stop database layer (fallback$env_suffix)" \
            "cd .. && docker compose --env-file docker-compose-azerothcore-database${env_suffix}.env -f docker-compose-azerothcore-database.yml down --remove-orphans || true"
    done

    # Clean up any remaining containers using container names from config
    if [ -n "$CONTAINER_MYSQL" ]; then
        local all_containers=($(get_all_container_names))
        for container in "${all_containers[@]}"; do
            execute_command "Remove container: $container" \
                "docker rm -f $container || true"
        done
    fi

    # Clean up networks
    if [ -n "$NETWORK_NAME" ]; then
        execute_command "Remove network: $NETWORK_NAME" \
            "docker network rm $NETWORK_NAME || true"
    fi

    execute_command "Remove any remaining AzerothCore networks" \
        "docker network ls --format '{{.Name}}' | grep -E 'azerothcore|acore' | xargs -r docker network rm || true"

    print_status "SUCCESS" "Cleanup completed"
}

# Function to wait for a service to be ready
wait_for_service() {
    local service_name=$1
    local max_attempts=$2
    local check_command=$3

    print_status "INFO" "Waiting for $service_name to be ready..."

    for i in $(seq 1 $max_attempts); do
        if eval "$check_command" &>/dev/null; then
            print_status "SUCCESS" "$service_name is ready!"
            return 0
        fi

        if [ $i -eq $max_attempts ]; then
            print_status "ERROR" "$service_name failed to start after $max_attempts attempts"
            return 1
        fi

        echo -n "."
        sleep 5
    done
}

# Function to check port connectivity using the actual configured ports
check_port() {
    local port=$1
    local service_name=$2
    local timeout=${3:-5}

    if timeout $timeout bash -c "echo >/dev/tcp/$SERVER_ADDRESS/$port" 2>/dev/null; then
        print_status "SUCCESS" "$service_name ($SERVER_ADDRESS:$port): CONNECTED"
        return 0
    else
        print_status "ERROR" "$service_name ($SERVER_ADDRESS:$port): FAILED"
        return 1
    fi
}

# Function to deploy the stack
deploy_stack() {
    print_status "HEADER" "DEPLOYING AZEROTHCORE STACK"

    # Verify environment files exist
    if ! check_env_files; then
        print_status "ERROR" "Required environment files are missing"
        if [ "$ENV_TYPE" = "none" ]; then
            print_status "INFO" "Run without --skip-wizard to generate custom environment files"
        fi
        exit 1
    fi

    # Load deployment configuration
    get_deployment_config

    print_status "INFO" "Step 1: Deploying database layer..."
    execute_command "Deploy database layer" \
        "cd .. && docker compose --env-file docker-compose-azerothcore-database${ENV_FILES_BASE}.env -f docker-compose-azerothcore-database.yml up -d"

    if [ "$DRY_RUN" = false ]; then
        # Wait for database initialization using actual container name and credentials
        wait_for_service "MySQL ($CONTAINER_MYSQL)" 24 "docker exec $CONTAINER_MYSQL mysql -u$MYSQL_USER -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1' >/dev/null 2>&1"

        # Wait for database import using actual container name
        wait_for_service "Database Import ($CONTAINER_DB_IMPORT)" 36 "docker logs $CONTAINER_DB_IMPORT 2>/dev/null | grep -q 'Database import complete'"
    fi

    print_status "INFO" "Step 2: Deploying services layer..."
    execute_command "Deploy services layer" \
        "cd .. && docker compose --env-file docker-compose-azerothcore-services${ENV_FILES_BASE}.env -f docker-compose-azerothcore-services.yml up -d"

    if [ "$DRY_RUN" = false ]; then
        # Wait for client data extraction using actual container name
        print_status "INFO" "Waiting for client data download and extraction (this may take 10-20 minutes)..."
        wait_for_service "Client Data ($CONTAINER_CLIENT_DATA)" 120 "docker logs $CONTAINER_CLIENT_DATA 2>/dev/null | grep -q 'Game data setup complete'"

        # Wait for worldserver to be healthy using actual container name
        wait_for_service "World Server ($CONTAINER_WORLDSERVER)" 24 "docker inspect --format='{{.State.Health.Status}}' $CONTAINER_WORLDSERVER 2>/dev/null | grep -q healthy"
    fi

    # Deploy modules layer if environment file exists
    local modules_file="docker-compose-azerothcore-modules${ENV_FILES_BASE}.env"
    if [ -f "../$modules_file" ]; then
        print_status "INFO" "Step 3: Deploying modules layer..."
        execute_command "Deploy modules layer" \
            "cd .. && docker compose --env-file $modules_file -f docker-compose-azerothcore-modules.yml up -d"

        if [ "$DRY_RUN" = false ] && [ -n "$CONTAINER_MODULES" ]; then
            # Wait for modules setup using actual container name
            wait_for_service "Modules Setup ($CONTAINER_MODULES)" 12 "docker logs $CONTAINER_MODULES 2>/dev/null | grep -q 'Module configuration complete'"
        fi
    else
        print_status "INFO" "Step 3: Skipping modules layer (vanilla deployment)"
    fi

    print_status "INFO" "Step 4: Deploying tools layer..."
    execute_command "Deploy tools layer" \
        "cd .. && docker compose --env-file docker-compose-azerothcore-tools${ENV_FILES_BASE}.env -f docker-compose-azerothcore-tools.yml up -d"

    if [ "$DRY_RUN" = false ]; then
        # Wait for tools to be ready
        sleep 10
    fi

    print_status "SUCCESS" "Deployment completed!"
}

# Function to perform health checks using actual configuration
perform_health_checks() {
    print_status "HEADER" "PERFORMING HEALTH CHECKS"

    local total_failures=0

    # Container health checks using actual container names
    local containers=($(get_all_container_names))
    for container in "${containers[@]}"; do
        if docker ps --format '{{.Names}}' | grep -q "^${container}$" 2>/dev/null; then
            local status=$(docker inspect --format='{{.State.Health.Status}}' $container 2>/dev/null || echo "no-health-check")
            if [ "$status" = "healthy" ]; then
                print_status "SUCCESS" "$container: healthy"
            elif [ "$status" = "no-health-check" ] || [ "$status" = "<no value>" ]; then
                print_status "SUCCESS" "$container: running (no health check)"
            else
                print_status "WARNING" "$container: $status"
                ((total_failures++))
            fi
        fi
    done

    # Database Layer
    print_status "INFO" "Database Layer:"
    if ! check_port "$MYSQL_EXTERNAL_PORT" "MySQL"; then ((total_failures++)); fi

    # Services Layer
    print_status "INFO" "Services Layer:"
    if ! check_port "$AUTH_EXTERNAL_PORT" "Auth Server"; then ((total_failures++)); fi
    if ! check_port "$WORLD_EXTERNAL_PORT" "World Server"; then ((total_failures++)); fi
    if ! check_port "$SOAP_EXTERNAL_PORT" "SOAP API"; then ((total_failures++)); fi

    # Tools Layer
    print_status "INFO" "Tools Layer:"
    if ! check_port "$PMA_EXTERNAL_PORT" "PHPMyAdmin"; then ((total_failures++)); fi
    if ! check_port "$KEIRA3_EXTERNAL_PORT" "Keira3"; then ((total_failures++)); fi

    # Database connectivity test using actual credentials and database names
    print_status "INFO" "Database Connectivity:"
    if docker exec $CONTAINER_MYSQL mysql -u$MYSQL_USER -p$MYSQL_ROOT_PASSWORD -e "SHOW DATABASES;" 2>/dev/null | grep -q "$DB_AUTH_NAME"; then
        print_status "SUCCESS" "Database schemas: verified ($DB_AUTH_NAME, $DB_WORLD_NAME, $DB_CHARACTERS_NAME)"
    else
        print_status "ERROR" "Database schemas: verification failed"
        ((total_failures++))
    fi

    return $total_failures
}

# Function to show deployment summary
show_deployment_summary() {
    print_status "HEADER" "DEPLOYMENT SUMMARY"

    if [ "$DRY_RUN" = true ]; then
        print_status "INFO" "Dry run completed - no actual deployment performed"
        return 0
    fi

    # Load configuration
    get_deployment_config

    # Perform health checks
    if perform_health_checks; then
        print_status "SUCCESS" "All services are healthy and operational!"
    else
        print_status "WARNING" "Some services may have connectivity issues"
    fi

    print_status "INFO" "Available services:"
    echo "  🌐 PHPMyAdmin:     http://$SERVER_ADDRESS:$PMA_EXTERNAL_PORT"
    echo "  🛠️  Keira3:         http://$SERVER_ADDRESS:$KEIRA3_EXTERNAL_PORT"
    echo "  🎮 Game Server:    $SERVER_ADDRESS:$WORLD_EXTERNAL_PORT"
    echo "  🔐 Auth Server:    $SERVER_ADDRESS:$AUTH_EXTERNAL_PORT"
    echo "  🔧 SOAP API:       $SERVER_ADDRESS:$SOAP_EXTERNAL_PORT"
    echo "  🗄️  MySQL:          $SERVER_ADDRESS:$MYSQL_EXTERNAL_PORT"
    echo ""
    print_status "INFO" "Database information:"
    echo "  🗄️  Host: $MYSQL_HOST"
    echo "  🗄️  User: $MYSQL_USER"
    echo "  🗄️  Password: $MYSQL_ROOT_PASSWORD"
    echo "  🗄️  Databases: $DB_AUTH_NAME, $DB_WORLD_NAME, $DB_CHARACTERS_NAME"
    echo ""

    # Show container status
    print_status "INFO" "Container Status:"
    local containers=($(get_all_container_names))
    for container in "${containers[@]}"; do
        if docker ps --format '{{.Names}}' | grep -q "^${container}$" 2>/dev/null; then
            docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep "^${container}" || true
        fi
    done
    echo ""

    # Check if modules are enabled
    if [ -f "../docker-compose-azerothcore-modules${ENV_FILES_BASE}.env" ]; then
        print_status "INFO" "Modules are enabled - server includes enhancements"
    else
        print_status "INFO" "Vanilla mode - no modules enabled"
    fi

    print_status "SUCCESS" "🎉 AzerothCore deployment is complete!"
    print_status "INFO" "Configure your WoW 3.3.5a client: set realmlist $SERVER_ADDRESS"
}

# Main execution
main() {
    print_status "HEADER" "AZEROTHCORE CUSTOM ENVIRONMENT DEPLOYMENT"

    # Check if docker is available
    if ! command -v docker &> /dev/null; then
        print_status "ERROR" "Docker is not installed or not in PATH"
        exit 1
    fi

    # Check if docker compose is available
    if ! docker compose version &> /dev/null; then
        print_status "ERROR" "Docker Compose is not available"
        exit 1
    fi

    # Perform cleanup if requested
    if [ "$CLEANUP_FIRST" = true ]; then
        perform_cleanup
    fi

    # Run setup wizard unless skipped
    if [ "$SKIP_WIZARD" = false ]; then
        run_setup_wizard
    elif ! detect_env_files || ! check_env_files; then
        print_status "ERROR" "Required environment files not found and --skip-wizard specified"
        print_status "INFO" "Either run without --skip-wizard or generate environment files first"
        exit 1
    fi

    # Deploy the stack
    deploy_stack

    # Show deployment summary
    show_deployment_summary
}

# Run main function
main "$@"